### ISSUE TITLE
Replace in files hidden

### ISSUE THREAD

**Issue by ThomasRobertFr** [varemenos/sublime-predawn-monokai#1]
Hello,

When using this theme, the "replace" field in "search and replace in files" toolbar is hidden.

![Before](http://static.squarespace.com/static/4f56899824acca1952a81f21/t/53d8d08ae4b04f5aae30afb1/1406718090873/sublime-search-replace)

![After](http://i.imgur.com/743SU79.png?1)

Could it be possible to fix it?

**Comment by varemenos** [comment]
It actually isn't hidden. Try resizing the find/replace dialog by raising it a bit, you will see it will reflow.

**Comment by ThomasRobertFr** [comment]
Oh yes, you're right, I didn't thought it was possible to resize it.

Sorry for the missreport then, and thanks for the trick!
